// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VolunteerMatch.Data;

#nullable disable

namespace VolunteerMatch.Migrations
{
    [DbContext(typeof(VolunteerMatchDbContext))]
    partial class VolunteerMatchDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VolunteerMatch.Models.Cause", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Causes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "vitae imperdiet augue vulputate vel. Morbi.",
                            ImageUrl = "https://www.mccanndogs.com/cdn/shop/articles/living-with-cats-dogs-689902.jpg?v=1680325849",
                            Name = "Animals"
                        },
                        new
                        {
                            Id = 2,
                            Description = "vel dignissim nulla scelerisque a. Ut in ante mattis",
                            ImageUrl = "https://cff2.earth.com/uploads/2018/07/25115124/Kids-now-spend-twice-as-much-time-playing-indoors-than-outdoors.jpg",
                            Name = "Children & Youth"
                        },
                        new
                        {
                            Id = 3,
                            Description = "consectetur adipiscing elit. Praesent rutrum nibh lacus",
                            ImageUrl = "https://theculturalcourier.home.blog/wp-content/uploads/2019/07/culture-and-edcucation.png?w=640",
                            Name = "Cultural & Education"
                        },
                        new
                        {
                            Id = 4,
                            Description = "euismod mi. Phasellus blandit lacinia pharetra. Vestibulum mollis finibus metus",
                            ImageUrl = "https://www.stronggo.com/sites/default/files/2023-01/shutterstock_716571097.jpg",
                            Name = "Disabilities"
                        },
                        new
                        {
                            Id = 5,
                            Description = "consectetur adipiscing elit. Praesent rutrum nibh lacus",
                            ImageUrl = "https://imageio.forbes.com/blogs-images/dennismersereau/files/2017/03/C8GOcZ7VYAEAFbc-1200x900.jpg?format=jpg&height=600&width=1200&fit=bounds",
                            Name = "Disaster Relief"
                        },
                        new
                        {
                            Id = 6,
                            Description = "vitae imperdiet augue vulputate vel. Morbi.",
                            ImageUrl = "https://www.investopedia.com/thmb/V_F1Tyf6FqF6fV55_2P353jdjdA=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/GettyImages-557921071-5689c4873df78ccc15334caf.jpg",
                            Name = "Elderly"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Lorem ipsum dolor sit amet",
                            ImageUrl = "https://images.nationalgeographic.org/image/upload/v1638890315/EducationHub/photos/amazon-river-basin.jpg",
                            Name = "Environment"
                        },
                        new
                        {
                            Id = 8,
                            Description = "bibendum libero non",
                            ImageUrl = "https://i0.wp.com/calmatters.org/wp-content/uploads/2023/07/071223-Homeless-Camp-LA-JAH-CM-40.jpg?fit=2000%2C1333&ssl=1",
                            Name = "Homelessness"
                        },
                        new
                        {
                            Id = 9,
                            Description = "bibendum libero non",
                            ImageUrl = "https://i.unu.edu/media/ourworld.unu.edu-en/article/148/Hunger-and-poverty-overshadowed.jpg",
                            Name = "Hunger & Poverty"
                        },
                        new
                        {
                            Id = 10,
                            Description = "bibendum libero non",
                            ImageUrl = "https://scx2.b-cdn.net/gfx/news/hires/2018/3-bacteria.jpg",
                            Name = "Health & Disease"
                        });
                });

            modelBuilder.Entity("VolunteerMatch.Models.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CauseId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsFollowing")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CauseId");

                    b.ToTable("Organizations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CauseId = 1,
                            Description = "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
                            ImageURL = "https://eu-images.contentstack.com/v3/assets/blte5a51c2d28bbcc9c/bltbf9b120b9c69987f/6647853f1bf9d6ed16038bc6/Feeding_America.png?disable=upscale&width=1200&height=630&fit=crop",
                            IsFollowing = false,
                            Location = "Room 1448",
                            Name = "Feeding America"
                        },
                        new
                        {
                            Id = 2,
                            CauseId = 2,
                            Description = "Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.",
                            ImageURL = "https://good360.org/wp-content/uploads/2020/11/Good360-Logo-500x.jpg",
                            IsFollowing = false,
                            Location = "5th Floor",
                            Name = "Good 360"
                        },
                        new
                        {
                            Id = 3,
                            CauseId = 3,
                            Description = "Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.",
                            ImageURL = "https://mma.prnewswire.com/media/613525/St_Jude_Childrens_Research_Hospital_Logo.jpg?p=twitter",
                            IsFollowing = false,
                            Location = "Suite 29",
                            Name = "St. Jude Children's Research Hospital"
                        },
                        new
                        {
                            Id = 4,
                            CauseId = 4,
                            Description = "Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.",
                            ImageURL = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/United_Way_Worldwide_logo.svg/1200px-United_Way_Worldwide_logo.svg.png",
                            IsFollowing = false,
                            Location = "Apt 1957",
                            Name = "United Way Worldwide"
                        },
                        new
                        {
                            Id = 5,
                            CauseId = 5,
                            Description = "Fusce consequat. Nulla nisl. Nunc nisl.",
                            ImageURL = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2fOL-c3xiQ-mY3AY8sZW2f-Wazzmz_tP6cw&s",
                            IsFollowing = false,
                            Location = "Room 399",
                            Name = "Direct Relief"
                        },
                        new
                        {
                            Id = 6,
                            CauseId = 6,
                            Description = "In congue. Etiam justo. Etiam pretium iaculis justo.",
                            ImageURL = "https://upload.wikimedia.org/wikipedia/en/thumb/c/c4/The_Salvation_Army.svg/1200px-The_Salvation_Army.svg.png",
                            IsFollowing = false,
                            Location = "Room 418",
                            Name = "Salvation Army"
                        },
                        new
                        {
                            Id = 7,
                            CauseId = 7,
                            Description = "Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.",
                            ImageURL = "https://over50andoverseas.com/wp-content/uploads/2018/11/habitat-for-humanity-logo.jpg",
                            IsFollowing = false,
                            Location = "PO Box 9244",
                            Name = "Habitat for Humanity International"
                        },
                        new
                        {
                            Id = 8,
                            CauseId = 8,
                            Description = "Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.",
                            ImageURL = "https://www.americares.org/wp-content/uploads/Americares-Logo_02big.gif",
                            IsFollowing = false,
                            Location = "17th Floor",
                            Name = "Americares"
                        },
                        new
                        {
                            Id = 9,
                            CauseId = 9,
                            Description = "Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.",
                            ImageURL = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTv032LFny9_SAG8KQK6-jiOd4Ku65DmBX43Q&s",
                            IsFollowing = false,
                            Location = "Suite 68",
                            Name = "Goodwill Industries International"
                        },
                        new
                        {
                            Id = 10,
                            CauseId = 10,
                            Description = "In congue. Etiam justo. Etiam pretium iaculis justo.",
                            ImageURL = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNPs6VOZGUeyc0jibA4r7JN-2zt_BP_OAssQ&s",
                            IsFollowing = false,
                            Location = "Suite 37",
                            Name = "Boys & Girls Clubs of America"
                        });
                });

            modelBuilder.Entity("VolunteerMatch.Models.OrganizationFollower", b =>
                {
                    b.Property<int>("VolunteerId")
                        .HasColumnType("integer");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.HasKey("VolunteerId", "OrganizationId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("OrganizationFollowers");

                    b.HasData(
                        new
                        {
                            VolunteerId = 1,
                            OrganizationId = 1
                        },
                        new
                        {
                            VolunteerId = 1,
                            OrganizationId = 2
                        },
                        new
                        {
                            VolunteerId = 1,
                            OrganizationId = 3
                        },
                        new
                        {
                            VolunteerId = 1,
                            OrganizationId = 4
                        },
                        new
                        {
                            VolunteerId = 5,
                            OrganizationId = 1
                        },
                        new
                        {
                            VolunteerId = 6,
                            OrganizationId = 5
                        },
                        new
                        {
                            VolunteerId = 7,
                            OrganizationId = 5
                        },
                        new
                        {
                            VolunteerId = 8,
                            OrganizationId = 5
                        },
                        new
                        {
                            VolunteerId = 9,
                            OrganizationId = 5
                        },
                        new
                        {
                            VolunteerId = 10,
                            OrganizationId = 5
                        });
                });

            modelBuilder.Entity("VolunteerMatch.Models.Volunteer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Volunteers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "mscotchforth0@unicef.org",
                            FirstName = "Moshe",
                            ImageUrl = "https://www.wsaz.com/resizer/TtxT5eHIfsdlCYPQRJG_wdDg9yQ=/arc-photo-gray/arc3-prod/public/FLBGRRRDQNHYBNTNHU4WOWRIFY.png",
                            LastName = "Scotchforth",
                            Uid = "8a46acbf-bea8-49ea-87e7-bd62d6352be5"
                        },
                        new
                        {
                            Id = 2,
                            Email = "nnormanvell1@un.org",
                            FirstName = "Natalya",
                            ImageUrl = "https://www.wsaz.com/resizer/TtxT5eHIfsdlCYPQRJG_wdDg9yQ=/arc-photo-gray/arc3-prod/public/FLBGRRRDQNHYBNTNHU4WOWRIFY.png",
                            LastName = "Normanvell",
                            Uid = "eabedf0d-6e38-4d3a-bd2b-c707ab8f79c0"
                        },
                        new
                        {
                            Id = 3,
                            Email = "alow2@vkontakte.ru",
                            FirstName = "Alyda",
                            ImageUrl = "https://www.wsaz.com/resizer/TtxT5eHIfsdlCYPQRJG_wdDg9yQ=/arc-photo-gray/arc3-prod/public/FLBGRRRDQNHYBNTNHU4WOWRIFY.png",
                            LastName = "Low",
                            Uid = "2844319a-349d-4620-a18b-9976d751a0cb"
                        },
                        new
                        {
                            Id = 4,
                            Email = "rstavers3@illinois.edu",
                            FirstName = "Roch",
                            ImageUrl = "https://www.wsaz.com/resizer/TtxT5eHIfsdlCYPQRJG_wdDg9yQ=/arc-photo-gray/arc3-prod/public/FLBGRRRDQNHYBNTNHU4WOWRIFY.png",
                            LastName = "Stavers",
                            Uid = "5777d6e9-5c33-4c02-bf4d-65c688d09090"
                        },
                        new
                        {
                            Id = 5,
                            Email = "ghowman4@ed.gov",
                            FirstName = "Garrard",
                            ImageUrl = "https://www.wsaz.com/resizer/TtxT5eHIfsdlCYPQRJG_wdDg9yQ=/arc-photo-gray/arc3-prod/public/FLBGRRRDQNHYBNTNHU4WOWRIFY.png",
                            LastName = "Howman",
                            Uid = "465386f6-970b-46e3-a45a-c02c91d86fdc"
                        },
                        new
                        {
                            Id = 6,
                            Email = "adarling5@gnu.org",
                            FirstName = "Alana",
                            ImageUrl = "https://www.wsaz.com/resizer/TtxT5eHIfsdlCYPQRJG_wdDg9yQ=/arc-photo-gray/arc3-prod/public/FLBGRRRDQNHYBNTNHU4WOWRIFY.png",
                            LastName = "Darling",
                            Uid = "b3119942-065c-4a74-bbb8-7a85f7eebd23"
                        },
                        new
                        {
                            Id = 7,
                            Email = "mgothrup6@51.la",
                            FirstName = "Malachi",
                            ImageUrl = "https://www.wsaz.com/resizer/TtxT5eHIfsdlCYPQRJG_wdDg9yQ=/arc-photo-gray/arc3-prod/public/FLBGRRRDQNHYBNTNHU4WOWRIFY.png",
                            LastName = "Gothrup",
                            Uid = "03aa171b-e27b-4f65-8abb-6f9070213ad5"
                        },
                        new
                        {
                            Id = 8,
                            Email = "bshelmerdine7@woothemes.com",
                            FirstName = "Bryon",
                            ImageUrl = "https://www.wsaz.com/resizer/TtxT5eHIfsdlCYPQRJG_wdDg9yQ=/arc-photo-gray/arc3-prod/public/FLBGRRRDQNHYBNTNHU4WOWRIFY.png",
                            LastName = "Shelmerdine",
                            Uid = "7bae8314-31c4-4e72-bb8b-c012f4ae808e"
                        },
                        new
                        {
                            Id = 9,
                            Email = "adalesio8@smh.com.au",
                            FirstName = "Abigail",
                            ImageUrl = "https://www.wsaz.com/resizer/TtxT5eHIfsdlCYPQRJG_wdDg9yQ=/arc-photo-gray/arc3-prod/public/FLBGRRRDQNHYBNTNHU4WOWRIFY.png",
                            LastName = "D'Alesio",
                            Uid = "75173053-1802-4ab3-957a-7bbe64992b64"
                        },
                        new
                        {
                            Id = 10,
                            Email = "vdisley9@skype.com",
                            FirstName = "Valeda",
                            ImageUrl = "https://www.wsaz.com/resizer/TtxT5eHIfsdlCYPQRJG_wdDg9yQ=/arc-photo-gray/arc3-prod/public/FLBGRRRDQNHYBNTNHU4WOWRIFY.png",
                            LastName = "Disley",
                            Uid = "0175f3a4-ed7f-488e-8f1c-65c47106e994"
                        });
                });

            modelBuilder.Entity("VolunteerMatch.Models.Organization", b =>
                {
                    b.HasOne("VolunteerMatch.Models.Cause", "Cause")
                        .WithMany("Organizations")
                        .HasForeignKey("CauseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cause");
                });

            modelBuilder.Entity("VolunteerMatch.Models.OrganizationFollower", b =>
                {
                    b.HasOne("VolunteerMatch.Models.Organization", "Organization")
                        .WithMany("OrganizationFollowers")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolunteerMatch.Models.Volunteer", "Volunteer")
                        .WithMany("OrganizationFollowers")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("VolunteerMatch.Models.Cause", b =>
                {
                    b.Navigation("Organizations");
                });

            modelBuilder.Entity("VolunteerMatch.Models.Organization", b =>
                {
                    b.Navigation("OrganizationFollowers");
                });

            modelBuilder.Entity("VolunteerMatch.Models.Volunteer", b =>
                {
                    b.Navigation("OrganizationFollowers");
                });
#pragma warning restore 612, 618
        }
    }
}
